import 'package:hive/hive.dart';

part 'folder.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 1) // Unique typeId (different from Note)
class Folder extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String name;

  @HiveField(2)
  int colorValue; // Store color as an integer (e.g., 0xFFRRGGBB)

  Folder({
    required this.id,
    required this.name,
    required this.colorValue,
  });

  // Optional: copyWith method
  Folder copyWith({
    String? id,
    String? name,
    int? colorValue,
  }) {
    return Folder(
      id: id ?? this.id,
      name: name ?? this.name,
      colorValue: colorValue ?? this.colorValue,
    );
  }

   @override
  String toString() {
    return 'Folder(id: $id, name: $name, colorValue: $colorValue)';
  }
}
