import 'package:hive/hive.dart';

part 'note.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 0) // Unique typeId for Hive
class Note extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String title;

  @HiveField(2)
  String content;

  @HiveField(3)
  DateTime creationDate;

  @HiveField(4) // New field index
  DateTime lastModified;

  // Link to Folder (optional)
  @HiveField(5) // Incremented index
  String? folderId;

  @HiveField(6) // New field for trash status
  bool isDeleted;

  Note({
    required this.id,
    required this.title,
    required this.content,
    required this.creationDate,
    DateTime? lastModified, // Make optional for existing data
    this.folderId,
    this.isDeleted = false, // Default to not deleted
  }) : lastModified = lastModified ?? creationDate; // Default to creationDate if not provided

  // Optional: Add a copyWith method for easier updates
  Note copyWith({
    String? id,
    String? title,
    String? content,
    DateTime? creationDate,
    DateTime? lastModified, // Added
    String? folderId, // Use null to remove folder association
    bool setFolderIdToNull = false, // Explicit flag to set folderId to null
    bool? isDeleted,
  }) {
    return Note(
      id: id ?? this.id,
      title: title ?? this.title,
      content: content ?? this.content,
      creationDate: creationDate ?? this.creationDate,
      lastModified: lastModified ?? this.lastModified, // Update last modified
      folderId: setFolderIdToNull ? null : folderId ?? this.folderId,
      isDeleted: isDeleted ?? this.isDeleted,
    );
  }

  @override
  String toString() {
    return 'Note(id: $id, title: $title, creationDate: $creationDate, folderId: $folderId, isDeleted: $isDeleted)';
  }
}
